// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAeyFBkrUVELDvygUIXFsw97c3BzeZvpEU',
    appId: '1:342533282072:web:65b16a46dbfce524a5a66d',
    messagingSenderId: '342533282072',
    projectId: 'notiftenangkan',
    authDomain: 'notiftenangkan.firebaseapp.com',
    storageBucket: 'notiftenangkan.firebasestorage.app',
    measurementId: 'G-DC35QNTWZD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAaE2QrF8sShphy5JbX8f41oEo0D3vZmBc',
    appId: '1:342533282072:android:af239ea27f93b35fa5a66d',
    messagingSenderId: '342533282072',
    projectId: 'notiftenangkan',
    storageBucket: 'notiftenangkan.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6GTWKy6A4GtJyVgRXx5Jiw_9p9vk1_xo',
    appId: '1:342533282072:ios:a22ad37e8a9e1c74a5a66d',
    messagingSenderId: '342533282072',
    projectId: 'notiftenangkan',
    storageBucket: 'notiftenangkan.firebasestorage.app',
    iosBundleId: 'com.example.tenangkan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6GTWKy6A4GtJyVgRXx5Jiw_9p9vk1_xo',
    appId: '1:342533282072:ios:a22ad37e8a9e1c74a5a66d',
    messagingSenderId: '342533282072',
    projectId: 'notiftenangkan',
    storageBucket: 'notiftenangkan.firebasestorage.app',
    iosBundleId: 'com.example.tenangkan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAeyFBkrUVELDvygUIXFsw97c3BzeZvpEU',
    appId: '1:342533282072:web:06c454ac069aafcba5a66d',
    messagingSenderId: '342533282072',
    projectId: 'notiftenangkan',
    authDomain: 'notiftenangkan.firebaseapp.com',
    storageBucket: 'notiftenangkan.firebasestorage.app',
    measurementId: 'G-TGB6F5DB7D',
  );
}
